import assert from 'node:assert/strict';
import { PostgresConfigurationAuthoring,provisionConfigurationCatalog } from '@/src/infrastructure/postgres/postgres-configuration-authoring';
import { configurationCandidate,configurationEditorKeys,type ConfigurationMutation } from '@/src/application/configuration-authoring';
import { ConfigurationManagementCommands } from '@/src/domain/reference';
import { definitions } from '@/src/mock/reference';
import { DxtApplication } from '@/src/application/dxt-application';
import { ApplicationError } from '@/src/application/repository-ports';
import { createProductionSliceRepositories } from '@/src/infrastructure/postgres/postgres-repositories';
import { hydrateConfigurationPackages } from '@/src/infrastructure/postgres/configuration-hydrator';
import { selectStudyReferenceSet,resolvedStudySetupItems,addStudySetupItem,updateStudySetupItem } from '@/src/features/experiment-series/study-setup-model';
import { packageAssembly } from '@/src/features/reference-studio/authoring-model';
import type { SqlDatabase } from '@/src/infrastructure/postgres/sql-database';
export async function productionConfigurationStudyContract(db:SqlDatabase){
 await provisionConfigurationCatalog(db,definitions);
 const boundary=new PostgresConfigurationAuthoring(db);
 const initial=await boundary.load();
 const proofs=[];
 for(const [slug,pin] of [['dts-improvement','config-package-photo-v1'],['adhesion-material-optimization','config-package-material-rd-v1']] as const){
  const app=new DxtApplication(createProductionSliceRepositories(db,await hydrateConfigurationPackages(db,[pin])));
  const original=(await app.studies.load(slug))!;
  const oldRun=await app.createRunFromStudy(slug,'STUDY_DEFAULT',`7a-old-${slug}`);
  const registry=(await boundary.load()).registry;
  const source=registry.packages.find(p=>p.id===pin)!;
  const sourceSet=registry.applicabilityRuleSets.find(s=>s.id===source.applicabilityRuleSetVersionIds[0])!;
  const item=original.operations.flatMap(o=>o.items).find(i=>i.editor==='NUMBER')!;
  const sourceRule=sourceSet.rules.find(r=>r.id===item.applicabilityId)!;
  const revisionId=`definition-7a-${slug}-v1`;
  const request:ConfigurationMutation={name:'createImmutableDefinitionRevision',input:{definitionId:`definition-7a-${slug}`,version:1,scope:source.scope,descriptor:{revisionId,label:`7A ${slug}`,editorKey:'NUMBER',unitDefinitionRevisionId:null,unit:'',intrinsicAllowedGrainRevisionIds:['grain-subject-r1'],intrinsicOptions:[]}}};
  await boundary.execute(request,`${slug}:definition`);
  await boundary.execute(request,`${slug}:definition`);
  await assert.rejects(boundary.execute({...request,input:{...request.input,descriptor:{...request.input.descriptor,label:'overwrite'}}},`${slug}:definition`));
  const set={...sourceSet,id:`${sourceSet.id}-7a`,version:Math.max(...registry.applicabilityRuleSets.filter(s=>s.code===sourceSet.code).map(s=>s.version))+1,status:'DRAFT' as const,rules:[...sourceSet.rules.map(rule=>({...rule,id:`${rule.id}-7a-adopted`})),{...sourceRule,id:`7a-rule-${slug}`,definitionRevisionId:revisionId,assignmentReferenceRevisionId:revisionId,defaultValue:'35',defaultRole:'FIXED' as const}]};
  await boundary.execute({name:'createApplicabilityRuleSetVersion',input:set},`${slug}:rule`);
  const version=Math.max(...registry.packages.filter(p=>p.packageId===source.packageId).map(p=>p.version))+1;
  const draft={id:`7a-draft-${slug}`,packageId:source.packageId,targetVersion:version,scope:source.scope};
  await boundary.execute({name:'createDraftPackage',input:draft},`${slug}:draft`);
  const newPin=`${source.packageId}-v${version}`;
  const assembly={...packageAssembly(source),definitionRevisionIds:[...source.definitionRevisionIds,revisionId],applicabilityRuleSetVersionIds:[set.id]};
  await boundary.execute({name:'assemblePackageVersion',input:{draftId:draft.id,packageVersionId:newPin,assembly}},`${slug}:assemble`);
  const candidate=configurationCandidate(await boundary.load());
  new ConfigurationManagementCommands(candidate,(await boundary.load()).catalog,configurationEditorKeys).validatePackageVersion(newPin);
  await boundary.execute({name:'activatePackageVersion',input:newPin},`${slug}:activate`);
  const snapshot=await boundary.load();
  await db.query("CREATE OR REPLACE FUNCTION fail_7a_activation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected activation failure'; END $$");
  await db.query('CREATE TRIGGER fail_7a_activation BEFORE INSERT ON configuration_activation FOR EACH ROW EXECUTE FUNCTION fail_7a_activation()');
  try {await assert.rejects(boundary.execute({name:'activatePackageVersion',input:pin},`${slug}:failed-activation`));}finally{await db.query('DROP TRIGGER fail_7a_activation ON configuration_activation');}
  assert.deepEqual(await boundary.load(),snapshot,'failed activation preserves all authoring and active state');
  await db.query("CREATE OR REPLACE FUNCTION fail_7a_receipt() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected configuration receipt failure'; END $$");
  await db.query('CREATE TRIGGER fail_7a_receipt BEFORE INSERT ON configuration_authoring_receipt FOR EACH ROW EXECUTE FUNCTION fail_7a_receipt()');
  try {await assert.rejects(boundary.execute({...request,input:{...request.input,version:2,descriptor:{...request.input.descriptor,revisionId:`${revisionId}-2`}}},`${slug}:failed-definition`));}finally{await db.query('DROP TRIGGER fail_7a_receipt ON configuration_authoring_receipt');}
  assert.deepEqual(await boundary.load(),snapshot,'definition/revision/receipt failure leaves no partial configuration');
  assert.equal(snapshot.registry.packages.find(p=>p.id===newPin)?.status,'ACTIVE');
  assert.equal(snapshot.authoredDefinitions.filter(d=>d.descriptor.revisionId===revisionId).length,1);
  assert.deepEqual((await hydrateConfigurationPackages(db,[pin])).getConfigurationRegistry().packages[0],initial.registry.packages.find(p=>p.id===pin));
  const configuration=await hydrateConfigurationPackages(db,[newPin]);
  const selected=selectStudyReferenceSet(original,newPin,configuration);
  assert.deepEqual(selected.operations.flatMap(o=>o.items).map(i=>[i.definitionRevisionId,i.value,i.intentRole]),original.operations.flatMap(o=>o.items).map(i=>[i.definitionRevisionId,i.value,i.intentRole]));
  await app.studies.save(selected,`${slug}:adopt`);
  const applicable=resolvedStudySetupItems(selected,item.operationId,configuration);
  const newItem=applicable.find(i=>i.definitionRevisionId===revisionId)!;
  assert.ok(newItem,'new persisted definition is resolved using stored Operation context');
  const next=addStudySetupItem(selected,item.operationId,newItem,configuration);
  await app.studies.save(next,`${slug}:setup`);
  await app.studies.save(next,`${slug}:setup`);
  assert.deepEqual(await app.studies.load(slug),next);
  const notReady=await app.repositories.study.getLifecycleReadiness!(slug,newPin);
  assert.equal(notReady.status,'NOT_READY');
  await assert.rejects(app.createRunFromStudy(slug,'STUDY_DEFAULT',`blocked-${slug}`),/lifecycle not ready/);
  const proposal=notReady.proposals.find(p=>p.packageVersionId===pin)!;
  assert.ok(proposal,'persisted exact proposal is required; never infer from fixtures');
  const confirmation={packageVersionId:newPin,sourceContextId:proposal.id,targetBindings:proposal.context.targetBindings,confirmed:true as const};
  await db.query("CREATE OR REPLACE FUNCTION fail_adoption_receipt() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected adoption failure'; END $$");
  await db.query('CREATE TRIGGER fail_adoption_receipt BEFORE INSERT ON study_reasoning_adoption FOR EACH ROW EXECUTE FUNCTION fail_adoption_receipt()');
  try{await assert.rejects(app.repositories.study.confirmReasoningContext!(slug,confirmation,{commandId:`confirm-fail-${slug}`}));}finally{await db.query('DROP TRIGGER fail_adoption_receipt ON study_reasoning_adoption');}
  assert.equal((await app.repositories.study.getLifecycleReadiness!(slug,newPin)).status,'NOT_READY','context insert rolls back with its confirmation receipt');
  await assert.rejects(app.repositories.study.confirmReasoningContext!(slug,{...confirmation,targetBindings:confirmation.targetBindings.map(b=>({...b,target:{...b.target,parameterDefinitionId:'missing-exact-parameter'}}))},{commandId:`confirm-invalid-${slug}`}));
  await app.repositories.study.confirmReasoningContext!(slug,confirmation,{commandId:`confirm-${slug}`});
  await app.repositories.study.confirmReasoningContext!(slug,confirmation,{commandId:`confirm-${slug}`});
  const ready=await app.repositories.study.getLifecycleReadiness!(slug,newPin);
  assert.equal(ready.status,'READY');assert.notEqual(ready.contextId,proposal.id);
  await assert.rejects(app.repositories.study.confirmReasoningContext!(slug,{...confirmation,targetBindings:confirmation.targetBindings.map(b=>({...b,target:{...b.target,threshold:999}}))},{commandId:`confirm-rewrite-${slug}`}));
  const newRun=await app.createRunFromStudy(slug,'STUDY_DEFAULT',`7a-new-${slug}`);
  assert.equal(newRun.configurationPackageVersionId,newPin);
  assert.ok(newRun.assignments.some(a=>a.referenceId===revisionId&&a.value==='35'));
  const changed=updateStudySetupItem(next,newItem.id,'36');
  await app.studies.save(changed,`${slug}:changed`);
  await assert.rejects(app.studies.save({...changed,updatedAt:'2026-09-17'},`${slug}:stale`),e=>e instanceof ApplicationError&&e.code==='CONFLICT');
  const newest=await app.createRunFromStudy(slug,'STUDY_DEFAULT',`7a-latest-${slug}`);
  assert.ok(newest.assignments.some(a=>a.referenceId===revisionId&&a.value==='36'));
  assert.deepEqual(await app.repositories.run.getSnapshot(newRun.id),newRun);
  assert.deepEqual(await app.repositories.run.getSnapshot(oldRun.id),oldRun);
  await db.query("CREATE OR REPLACE FUNCTION fail_7a_assignment() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected setup failure'; END $$");
  await db.query('CREATE TRIGGER fail_7a_assignment BEFORE INSERT ON study_setup_assignment FOR EACH ROW EXECUTE FUNCTION fail_7a_assignment()');
  try{await assert.rejects(app.studies.save(updateStudySetupItem(changed,newItem.id,'37'),`${slug}:rollback`));}finally{await db.query('DROP TRIGGER fail_7a_assignment ON study_setup_assignment');}
  assert.deepEqual(await app.studies.load(slug),changed);
  await boundary.execute({name:'deactivatePackageVersion',input:pin},`${slug}:deactivate-old`);
  assert.ok((await db.query<{package_version_id:string}>('SELECT package_version_id FROM configuration_activation WHERE package_version_id=$1 AND active_to IS NULL',[newPin])).rows.length,'deactivating an old exact version cannot close the current activation');
  await boundary.execute({...request,input:{...request.input,version:2,descriptor:{...request.input.descriptor,revisionId:`${revisionId}-2`,label:'Revised label'}}},`${slug}:revision-two`);
  const revised=await boundary.load();
  assert.equal(revised.authoredDefinitions.find(d=>d.descriptor.revisionId===revisionId)?.descriptor.label,request.input.descriptor.label);
  assert.deepEqual(await app.repositories.run.getSnapshot(newRun.id),newRun,'later definition revision leaves old Run exact context unchanged');
  proofs.push({slug,setup:changed,newRun:newest,oldRun,newPin});
 }
 return {proofs,configuration:await boundary.load()};
}
