import { z } from 'zod';
import { idSchema } from '../reference';
import { effectiveMeasurementValues, measurementDatasetSchema, measurementValueSchema, type MeasurementDataset, type MeasurementValidityDecision, type MeasurementValue } from './index';

export const measurementGroupSchema=z.object({id:idSchema,name:z.string().min(1),description:z.string().nullable(),experimentRunId:idSchema,waferSubjectId:idSchema.nullable(),measurementValueIds:z.array(idSchema).min(1),createdBy:z.string().min(1),createdAt:z.iso.datetime({offset:true})});
export const arithmeticExpressionSchema=z.object({operator:z.enum(['ADD','SUBTRACT','MULTIPLY','DIVIDE']),leftAlias:z.literal('A'),rightAlias:z.literal('B')});
export const preprocessingRecipeSchema=z.object({id:idSchema,name:z.string().min(1),description:z.string(),expression:arithmeticExpressionSchema,inputAliases:z.tuple([z.literal('A'),z.literal('B')]),resultParameterDefinitionId:idSchema.nullable(),resultParameterMetadata:z.object({displayName:z.string().min(1),unit:z.string().nullable()}).nullable(),active:z.boolean(),createdBy:z.string(),createdAt:z.iso.datetime({offset:true})});
export const preprocessingExecutionSchema=z.object({id:idSchema,experimentRunId:idSchema,recipeId:idSchema.nullable(),inlineExpression:arithmeticExpressionSchema,inputDatasetAId:idSchema,inputDatasetBId:idSchema,inputMode:z.enum(['EFFECTIVE','RAW']),resultDatasetId:idSchema,matchingRule:z.literal('SITE_IDENTITY'),matchedCount:z.number().int().nonnegative(),unmatchedA:z.array(idSchema),unmatchedB:z.array(idSchema),executedBy:z.string(),executedAt:z.iso.datetime({offset:true})});
export type MeasurementGroup=z.infer<typeof measurementGroupSchema>;
export type PreprocessingRecipe=z.infer<typeof preprocessingRecipeSchema>;
export type PreprocessingExecution=z.infer<typeof preprocessingExecutionSchema>;

function numeric(value:MeasurementValue){return value.value.dataType==='NUMBER'?value.value.value:null}
export function createMeasurementGroup(input:z.input<typeof measurementGroupSchema>,values:readonly MeasurementValue[]){const group=measurementGroupSchema.parse(input);for(const id of group.measurementValueIds)if(!values.some((value)=>value.id===id))throw new Error('Unresolved grouped measurement');return group}
export function executeArithmeticPreparation(input:{id:string;runId:string;recipe:PreprocessingRecipe|null;expression:z.infer<typeof arithmeticExpressionSchema>;datasetA:MeasurementDataset;datasetB:MeasurementDataset;valuesA:MeasurementValue[];valuesB:MeasurementValue[];decisions:MeasurementValidityDecision[];resultName:string;resultUnit:string|null;actor:string;at:string;inputMode?:'EFFECTIVE'|'RAW'}){
  const mode=input.inputMode??'EFFECTIVE',a=mode==='EFFECTIVE'?effectiveMeasurementValues(input.valuesA,input.decisions):input.valuesA,b=mode==='EFFECTIVE'?effectiveMeasurementValues(input.valuesB,input.decisions):input.valuesB;
  const bySiteB=new Map(b.filter((value)=>value.siteIdentity).map((value)=>[value.siteIdentity!,value])),matched=a.filter((value)=>value.siteIdentity&&bySiteB.has(value.siteIdentity));
  const resultDataset=measurementDatasetSchema.parse({id:`dataset-derived-${input.id}`,experimentRunId:input.runId,plannedExecutionItemId:null,executionEventId:null,measurementOperationDefinitionId:input.datasetB.measurementOperationDefinitionId,equipmentReference:null,measurementPoint:'CUSTOM',sourceSystem:'DXT LIMS',collectedAt:input.at,status:'COLLECTED',datasetOrigin:'DERIVED',preprocessingExecutionId:input.id});
  const calculate=(left:number,right:number)=>input.expression.operator==='ADD'?left+right:input.expression.operator==='SUBTRACT'?left-right:input.expression.operator==='MULTIPLY'?left*right:right===0?null:left/right;
  const resultValues=matched.flatMap((left,index)=>{const right=bySiteB.get(left.siteIdentity!)!,lv=numeric(left),rv=numeric(right);if(lv===null||rv===null)return[];const result=calculate(lv,rv);if(result===null)return[];return[measurementValueSchema.parse({id:`derived-${input.id}-${index}`,datasetId:resultDataset.id,waferSubjectId:left.waferSubjectId,physicalWaferId:left.physicalWaferId,parameterDefinitionId:null,value:{dataType:'NUMBER',value:Number(result.toFixed(6))},unitDefinitionId:null,granularity:'SITE',siteIdentity:left.siteIdentity,coordinateValues:left.coordinateValues,observedAt:input.at,sourceParameterReference:null,acquisitionMethod:'DERIVED',adHocParameter:{displayName:input.resultName,unit:input.resultUnit},sourceMeasurementValueIds:[left.id,right.id]})]});
  const sitesA=new Set(a.map((value)=>value.siteIdentity).filter(Boolean)),sitesB=new Set(b.map((value)=>value.siteIdentity).filter(Boolean));
  const execution=preprocessingExecutionSchema.parse({id:input.id,experimentRunId:input.runId,recipeId:input.recipe?.id??null,inlineExpression:input.expression,inputDatasetAId:input.datasetA.id,inputDatasetBId:input.datasetB.id,inputMode:mode,resultDatasetId:resultDataset.id,matchingRule:'SITE_IDENTITY',matchedCount:resultValues.length,unmatchedA:[...sitesA].filter((site)=>!sitesB.has(site)).map(String),unmatchedB:[...sitesB].filter((site)=>!sitesA.has(site)).map(String),executedBy:input.actor,executedAt:input.at});
  return {execution,resultDataset,resultValues};
}
