'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowLeft, Calculator, FolderPlus } from 'lucide-react';
import type { ExperimentContext } from '@/src/domain/experiment';
import { aggregateMeasurements, type StandardAggregationMethod } from '@/src/domain/measurement';
import { executeArithmeticPreparation, type MeasurementGroup, type PreprocessingRecipe } from '@/src/domain/measurement/preparation';
import { inspectionGroup, inspectionObservations, mockThkDelta, preparationDatasets, preparationValues, thkDeltaRecipe } from '@/src/mock/data-preparation';
import { Badge, runPath, Workspace } from '@/src/shared/ui/workspace';

export default function DataPreparationWorkspace({context}:{context:ExperimentContext}) {
  const [mode,setMode]=useState<'GROUP'|'CALCULATE'>('GROUP'),[groups,setGroups]=useState<MeasurementGroup[]>([inspectionGroup]),[recipes,setRecipes]=useState<PreprocessingRecipe[]>([thkDeltaRecipe]),[operator,setOperator]=useState<'ADD'|'SUBTRACT'|'MULTIPLY'|'DIVIDE'>('SUBTRACT'),[result,setResult]=useState(mockThkDelta),[stat,setStat]=useState<StandardAggregationMethod>('MEAN');
  const [groupName,setGroupName]=useState('RSA6420.01 Inspection Images'),[selected,setSelected]=useState(inspectionObservations.map((value)=>value.id));
  const calculate=()=>setResult(executeArithmeticPreparation({id:`prep-${Date.now()}`,runId:context.run.id,recipe:null,expression:{operator,leftAlias:'A',rightAlias:'B'},datasetA:preparationDatasets[0],datasetB:preparationDatasets[1],valuesA:preparationValues.filter((value)=>value.datasetId===preparationDatasets[0].id),valuesB:preparationValues.filter((value)=>value.datasetId===preparationDatasets[1].id),decisions:[],resultName:'DELTA_THK',resultUnit:'nm',actor:context.series.owner,at:new Date().toISOString()}));
  return <Workspace page="Run" run={context.run.runNumber}><div className="preparation-page-head"><div><Link className="back-link" href={`${runPath(context.run.runNumber)}#measurement-results`}><ArrowLeft size={13}/> Run #{context.run.runNumber} Measurements</Link><span className="eyebrow">OPTIONAL WORKSPACE</span><h1>Data Preparation</h1><p>Organize or transform measurements for analysis while preserving source data.</p></div><Badge tone="blue">{context.series.title} · Run #{context.run.runNumber}</Badge></div>
  <div className="preparation-tabs"><button className={mode==='GROUP'?'active':''} onClick={()=>setMode('GROUP')}><FolderPlus size={15}/> Group</button><button className={mode==='CALCULATE'?'active':''} onClick={()=>setMode('CALCULATE')}><Calculator size={15}/> Calculate</button></div>
  {mode==='GROUP'?<div className="preparation-two-column"><section className="prep-card"><span>CREATE GROUP</span><h2>Logical measurement collection</h2><label>Wafer<input value="RSA6420.01" readOnly/></label><div className="available-measurements"><b>Available measurements</b>{inspectionObservations.map((value)=><label key={value.id}><input type="checkbox" checked={selected.includes(value.id)} onChange={()=>setSelected((items)=>items.includes(value.id)?items.filter((id)=>id!==value.id):[...items,value.id])}/>{String(value.value.value)}</label>)}</div><label>Group name<input value={groupName} onChange={(event)=>setGroupName(event.target.value)}/></label><button className="primary-button" onClick={()=>setGroups((items)=>[...items,{...inspectionGroup,id:`group-${Date.now()}`,name:groupName,measurementValueIds:selected,createdAt:new Date().toISOString()}])}>Create Group</button><p className="prep-guidance">Grouping references existing observations. No values are copied or calculated.</p></section><section className="prep-card"><span>MEASUREMENT GROUPS</span>{groups.map((group)=><details key={group.id} open={group.id===inspectionGroup.id}><summary><b>{group.name}</b><small>Group · {group.measurementValueIds.length} observations</small></summary>{group.measurementValueIds.map((id)=><p key={id}>{String(inspectionObservations.find((value)=>value.id===id)?.value.value??id)}</p>)}<small>Created {group.createdAt.slice(11,16)} · {group.createdBy}</small></details>)}</section></div>:<CalculateWorkspace operator={operator} setOperator={setOperator} result={result} calculate={calculate} recipes={recipes} setRecipes={setRecipes} stat={stat} setStat={setStat}/>} 
  <section className="preparation-history"><span>PREPARATION HISTORY</span><div><b>THK Delta</b><small>A − B · 58 Sites · Created 15:32</small><Badge tone="blue">Derived</Badge></div><div><b>RSA6420.01 Inspection Images</b><small>Group · 3 observations · Created 14:10</small><Badge>Group</Badge></div></section></Workspace>;
}

function CalculateWorkspace({operator,setOperator,result,calculate,recipes,setRecipes,stat,setStat}:{operator:'ADD'|'SUBTRACT'|'MULTIPLY'|'DIVIDE';setOperator:(value:'ADD'|'SUBTRACT'|'MULTIPLY'|'DIVIDE')=>void;result:typeof mockThkDelta;calculate:()=>void;recipes:PreprocessingRecipe[];setRecipes:React.Dispatch<React.SetStateAction<PreprocessingRecipe[]>>;stat:StandardAggregationMethod;setStat:(value:StandardAggregationMethod)=>void}) {
  const symbols={ADD:'+',SUBTRACT:'−',MULTIPLY:'×',DIVIDE:'÷'};
  const representative=aggregateMeasurements(result.resultValues,stat);
  return <div className="calculation-workspace"><section className="prep-card calculation-config"><span>NEW CALCULATION</span><h2>Arithmetic preprocessing</h2><label>Saved Recipe<select onChange={(event)=>{const recipe=recipes.find((item)=>item.id===event.target.value);if(recipe)setOperator(recipe.expression.operator)}}><option value="">Inline calculation</option>{recipes.map((recipe)=><option key={recipe.id} value={recipe.id}>{recipe.name} · A {symbols[recipe.expression.operator]} B</option>)}</select></label><div className="source-datasets"><DatasetCard alias="A" point="PRE" sites={60} equipment="THK-01"/><select value={operator} onChange={(event)=>setOperator(event.target.value as typeof operator)}><option value="ADD">A + B</option><option value="SUBTRACT">A − B</option><option value="MULTIPLY">A × B</option><option value="DIVIDE">A ÷ B</option></select><DatasetCard alias="B" point="POST" sites={58} equipment="THK-02"/></div><label>Result parameter<input value="DELTA_THK" readOnly/></label><p className="prep-guidance">Inputs use the current Effective measurement state. Sources are selected explicitly and matched by identical Site ID.</p><div className="calculation-actions"><button className="secondary-button" onClick={()=>setRecipes((items)=>[...items,{...thkDeltaRecipe,id:`recipe-${Date.now()}`,expression:{operator,leftAlias:'A',rightAlias:'B'}}])}>Save as Recipe</button><button className="primary-button" onClick={calculate}>Run Calculation</button></div></section><section className="prep-card derived-result"><span>DERIVED MEASUREMENT DATASET</span><h2>DELTA_THK</h2><div className="match-summary"><div><small>Matched</small><b>{result.execution.matchedCount}</b></div><div><small>Unmatched A</small><b>{result.execution.unmatchedA.length}</b></div><div><small>Unmatched B</small><b>{result.execution.unmatchedB.length}</b></div></div><div className="aggregation-toggle">{(['MEAN','MEDIAN','MIN','MAX'] as const).map((item)=><button className={stat===item?'active':''} key={item} onClick={()=>setStat(item)}>{item}</button>)}</div><div className="derived-stat"><b>{representative?.toFixed(3)}</b><small>nm · {stat} · 58 matched Sites</small></div><div className="derived-table-wrap"><table><thead><tr><th>Site</th><th>A PRE</th><th>B POST</th><th>DELTA_THK</th><th>Lineage</th></tr></thead><tbody>{result.resultValues.slice(0,8).map((value)=><tr key={value.id}><td>{value.siteIdentity}</td><td>{preparationValues.find((item)=>item.id===value.sourceMeasurementValueIds[0])?.value.value}</td><td>{preparationValues.find((item)=>item.id===value.sourceMeasurementValueIds[1])?.value.value}</td><td><b>{value.value.value}</b> nm</td><td>{value.sourceMeasurementValueIds.join(' + ')}</td></tr>)}</tbody></table></div><p className="prep-warning">WARNING · Site59 and Site60 exist only in Source A. Matched Sites were calculated; unmatched Sites remain visible and unchanged.</p></section></div>;
}
function DatasetCard({alias,point,sites,equipment}:{alias:string;point:string;sites:number;equipment:string}){return <div className="dataset-source-card"><span>SOURCE {alias}</span><b>{point} Thickness · RSA6420.01</b><small>Lot RSA6420 · Thickness Metrology · THK · {sites} Sites · {equipment} · INTERFACE</small></div>}
